# Exported from Render on 2024-04-19T00:43:59Z
services:
- type: web
  name: tic-tac-toe-server
  runtime: node
  repo: https://github.com/SaiemAziz/tic-tac-toe-server
  plan: free
  envVars:
  - key: mongoURL
    sync: false
  region: singapore
  buildCommand: npm install
  startCommand: npm start
version: "1"
